GPU: [0]

VERBOSE: True

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 500
  LR_INITIAL: 4e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 128
  VAL_PS: 96
  TRAIN_DIR: './Datasets/Rain13k/train'       
  VAL_DIR: './Datasets/Rain13k/test/Rain100L'  
  SAVE_DIR: './checkpoints/Rain13k/PMDNet'